---
  - name: Preparation
    apt:
      name: libfontconfig1
      state: present

  - name: Download and install Grafana
    apt:
      deb: https://dl.grafana.com/oss/release/grafana_10.0.1_amd64.deb

  - name: Start and enable Grafana service
    systemd:
      name: grafana-server
      state: started
      enabled: yes

  - name: Configure Grafana provisioning directory
    file:
      path: /etc/grafana/provisioning/datasources
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Configure Grafana datasource
    template:
      src: grafana-datasource.yml.j2
      dest: /etc/grafana/provisioning/datasources/datasource.yml
      owner: root
      group: root
      mode: '0644'

  - name: Restart Grafana service
    systemd:
      name: grafana-server
      state: restarted