---
- hosts: webservers
  become: true

  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  
  roles:
    - { role: geerlingguy.nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: wordpress, tags: [wordpress, app] }