---
- name: reload privilages tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES

- name: remove anonymous users
  mysql_user: name="" host="{{ item }}" state=absent
  with_items: 
    - localhost
    - "{{ ansible_nodename }}"
 
- name: disallow root remote
  mysql_user: name=root host="{{ ansible_nodename }}" state=absent

- name: remove test databases
  mysql_db: db=test state=absent

- name: reload privileges tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES