---

  - name: install php
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "php{{php_version}}-fpm"
      - "php{{php_version}}-mysql"
      - "php{{php_version}}-xml"
      - "php{{php_version}}-curl"
      - "php{{php_version}}-gd"
      - "php{{php_version}}-mbstring"
      - "php{{php_version}}-readline"
      - "php{{php_version}}-bz2"
      - "php{{php_version}}-zip"
      - "php{{php_version}}-json"
      - "php{{php_version}}-opcache"
